name: octoprint-sdev
title: Octoprint
base: core18
summary: Octoprint the snappy web interface for your 3D printer
architectures:
  - build-on:
    - arm64
    - amd64
description: |
  # Full remote control & monitoring

  Control and monitor every aspect of your 3D printer and your printing jobs right from within your browser.

  # Compatible and extendable

  OctoPrint's powerful plugin system allows extending its functionality with awesome plugins from the community.

  # 100% Open Source

  Free and open source software released under the Affero General Public License (AGPL).

  # Compatible to Bosch Rexroth ctrlX CORE environment

  Integration into sidebar and reverse proxy environment
grade: stable
confinement: strict
adopt-info: version

parts:
  git-info:
    plugin: nil
    source: .
    override-build: |
      echo $(git rev-parse --abbrev-ref HEAD) > ${SNAPCRAFT_PART_INSTALL}/BRANCH
    stage:
      - BRANCH
  octoprint:
    plugin: python
    python-version: python3
    source: https://github.com/OctoPrint/OctoPrint.git
    override-pull: |
      export OCTOPRINT_VERSION=$(cat $SNAPCRAFT_STAGE/VERSION)
      snapcraftctl pull
      git checkout tags/${OCTOPRINT_VERSION}
    after:
    - configs
  configs:
    source: ./configs
    plugin: dump
    organize:
      'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/
  version:
    source: .
    plugin: nil
    override-stage: |
      if [ "$(cat BRANCH)" = "master" ]; then
        snapcraftctl set-grade "stable"
        snapcraftctl set-version "$(cat VERSION)+$(date +%Y%m%d%H%M)"
      else
        snapcraftctl set-grade "devel"
        snapcraftctl set-version "$(cat VERSION)-devel+$(date +%Y%m%d%H%M)"
      fi
    after:
    - git-info
    - configs
    - octoprint


apps:
  ctrlx-octoprint:
    command: usr/bin/python3 $SNAP/bin/octoprint serve -c $SNAP_DATA/config.yaml -b $SNAP_DATA/data --iknowwhatimdoing
    daemon: simple
    plugs: 
      - network-bind
      - mount-observe

plugs:
  usb-0:
    interface: serial-port

slots:
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
      - $SNAP/package-assets/${SNAPCRAFT_PROJECT_NAME}

layout:
  $SNAP/usr/lib/python3/dist-packages:
    bind: $SNAP_DATA/dist-packages
  $SNAP/usr/lib/python3/site-packages:
    bind: $SNAP_DATA/site-packages
  $SNAP/usr/local/lib/python3/dist-packages:
    bind: $SNAP_DATA/local/dist-packages
