name: octoprint-sdev
title: Octoprint
base: core22
summary: Octoprint the snappy web interface for your 3D printer
icon: snap/gui/logo.png
architectures:
  - amd64
  - arm64
description: |
  # Full remote control & monitoring

  Control and monitor every aspect of your 3D printer and your printing jobs right from within your browser.

  # Compatible and extendable

  OctoPrint's powerful plugin system allows extending its functionality with awesome plugins from the community.

  # 100% Open Source

  Free and open source software released under the Affero General Public License (AGPL).

  # Compatible to Bosch Rexroth ctrlX CORE environment

  Integration into sidebar and reverse proxy environment
confinement: strict
adopt-info: version
version: 1.9.2

parts:
  git-info:
    plugin: nil
    source: .
    override-build: |
      echo $(git rev-parse --abbrev-ref HEAD) > ${SNAPCRAFT_PART_INSTALL}/BRANCH
    stage:
      - BRANCH
  octoprint:
    plugin: python
    source: https://github.com/OctoPrint/OctoPrint.git
    python-requirements:
    - requirements.txt
    override-pull: |
      craftctl default
      git checkout tags/$(craftctl get version)
  configs:
    source: ./configs
    plugin: dump
    organize:
      'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/
  version:
    source: .
    plugin: nil
    override-stage: |
      if [ "$(cat BRANCH)" = "master" ]; then
        craftctl set grade "stable"
        craftctl set version "$(craftctl get version)"
      else
        craftctl set grade="devel"
        craftctl set version="$(craftctl get version)-devel+$(date +%Y%m%d%H%M)"
      fi
    after:
    - git-info
    - configs
    - octoprint


apps:
  ctrlx-octoprint:
    command: bin/python3 bin/octoprint serve -c $SNAP_DATA/config.yaml -b $SNAP_DATA/data --iknowwhatimdoing
    daemon: simple
    plugs: 
      - network-bind
      - mount-observe

plugs:
  usb-0:
    interface: serial-port

slots:
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
      - $SNAP/package-assets/${SNAPCRAFT_PROJECT_NAME}

layout:
  $SNAP/usr/lib/python3/dist-packages:
    bind: $SNAP_DATA/dist-packages
  $SNAP/usr/lib/python3/site-packages:
    bind: $SNAP_DATA/site-packages
  $SNAP/usr/local/lib/python3/dist-packages:
    bind: $SNAP_DATA/local/dist-packages
