name: Build

on: push

jobs:
  amd64:
    runs-on: ubuntu-18.04

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1

      # You can now run Snapcraft shell commands
      - name: Use Snapcraft
        run: snapcraft

      - uses: actions/upload-artifact@v2
        with:
          name: snapped
          path: '*.snap'
          if-no-files-found: error
          
  arm64:
    runs-on: ubuntu-18.04

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Snapcraft
        uses: samuelmeuli/action-snapcraft@v1

      # You can now run Snapcraft shell commands
      - name: Use Snapcraft
        run: snapcraft --target-arch=arm64

      - uses: actions/upload-artifact@v2
        with:
          name: snapped
          path: '*.snap'
          if-no-files-found: error
