name: Build

on: push

jobs:
#   amd64:
#     runs-on: ubuntu-18.04

#     steps:
#       - name: Check out Git repository
#         uses: actions/checkout@v2

#       - name: Install Snapcraft
#         uses: samuelmeuli/action-snapcraft@v1
#         with:
#           use_lxd: true

#       # You can now run Snapcraft shell commands
#       - name: Use Snapcraft
#         run: sg lxd -c 'snapcraft --use-lxd'


#       - uses: actions/upload-artifact@v2
#         with:
#           name: snapped
#           path: '*.snap'
#           if-no-files-found: error
          
        

  docker-job:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          image: tonistiigi/binfmt:latest
          platforms: all
      - uses: addnab/docker-run-action@v1
        with:
          image: adferrand/snapcraft:arm64v8-candidate
          run: uname -a
