#!/bin/bash -x

# Find a port 5000++
PORT=5000
while :; do nc -z localhost $PORT || break; PORT=$((PORT + 1));  done

snapctl set port="$PORT"

# Generate manifest
$SNAP/snap/command-chain/snapcraft-runner generate_manifest.sh